---

- include: dist_vars.yml

- include: install.yml

- name: copy tlp configuration
  template:
    src: "tlp.j2"
    dest: "/etc/default/tlp"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart tlp

- name: Ensure that tlp services are started and enabled on boot
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ tlp_services }}"
  when: tlp_enable

- name: Ensure that tlp triggered services are enabled on boot
  service:
    name: "{{ item }}"
    enabled: true
  with_items: "{{ tlp_triggered_services }}"
  when: tlp_enable

# vim: set ts=2 sw=2:
